print("Expressões Matemáticas")
print("#--------Adição---------#")
print(10+15)
print("#--------Subtração---------#")
print(1000-80)
print("#--------Mutiplicação---------#")
print(15*10)
print("#--------Divisão---------#")
print(10/5)
print(type(10/5))
print("utilizando // arredonda o valor para inteiro")
print(10//5)
print(type(10//5))